name: mlproject
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - scipy
  - joblib
  - pip
  - ipykernel
  - pip:
      - imbalanced-learn
      - jupyter
      - nbconvert
